version: '3'
services:
  firestore:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8081:8080"
  backend:
    build: ./backend
    environment:
      GOOGLE_CLOUD_PROJECT: local-project
      BUCKET_NAME: receipt-images
      FIRESTORE_EMULATOR_HOST: firestore:8080
    ports:
      - "8080:8080"
    depends_on:
      - firestore
