services:
  firestore:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8081:8080"
  storage:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators storage start --host-port=0.0.0.0:4443
    ports:
      - "4443:4443"
  backend:
    build: ./backend
    environment:
      GOOGLE_CLOUD_PROJECT: local-project
      BUCKET_NAME: receipt-images
      FIRESTORE_EMULATOR_HOST: firestore:8080
      STORAGE_EMULATOR_HOST: storage:4443
    ports:
      - "8080:8080"
    depends_on:
      - firestore
      - storage
